// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanDongHo.Web.Data;

#nullable disable

namespace WebBanDongHo.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260329044131_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBanDongHo.Web.Models.AppWatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("AppWatch", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = 1,
                            Name = "Orient Bambino Gen 2",
                            Price = 5600000m,
                            ShortDescription = "Mẫu dress watch cổ điển, kính cong và máy cơ tự động.",
                            Sku = "ORI-BAM-002",
                            Stock = 8
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = 1,
                            Name = "Tissot PRX Powermatic 80",
                            Price = 18500000m,
                            ShortDescription = "Thiết kế integrated bracelet hiện đại, dự trữ cót lên tới 80 giờ.",
                            Sku = "TIS-PRX-080",
                            Stock = 5
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastModifiedDate = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = 1,
                            Name = "Seiko 5 Sports SRPD55",
                            Price = 7900000m,
                            ShortDescription = "Dòng đồng hồ cơ bền bỉ, phong cách thể thao đa dụng.",
                            Sku = "SEI-5S-SRPD55",
                            Stock = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
